Update mangos

diff --git a/mangos b/mangos
--- a/mangos
+++ b/mangos
@@ -14,7 +14,7 @@
 
 # By Rainman
 # V20200302
-# 2.5.5.5
+# 2.6.0.1
 
 # Menusystem >
 
@@ -516,7 +516,7 @@ fi
 
 printf '%b' " <------------------------------------------------------------------------------>\e[31m
                     \e[0;32mCMaNGOS (Classic fork) - Command Center\e[31m
-            \e[0;33m[ C(ontinued)-MaNGOS Helper, admin helper tool v2.5.5.5 ]\033[0m
+            \e[0;33m[ C(ontinued)-MaNGOS Helper, admin helper tool v2.6.0.1 ]\033[0m
 
       $cm_uptime
 
@@ -856,7 +856,17 @@ esac
 
 "p")
 
-sudo apt-get install htop -y &> /dev/null
+which htop 2>&1|tee 1> /dev/null
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+sudo apt-get htop zip -y
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+echo -e "\e[42Installation failed\e[0m"
+fi
+fi
 htop
 
  ;;
@@ -1212,9 +1222,18 @@ fi
 
 # Update CMaNGOS ? >
 
-echo "checking.."
 # codes >
-sudo apt-get install dialog -y &> /dev/null
+which dialog 2>&1|tee 1> /dev/null
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+sudo apt-get install dialog -y
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+echo -e "\e[42Installation failed\e[0m"
+fi
+fi
 # codes done
 HEIGHT=15
 WIDTH=50
@@ -1368,7 +1387,6 @@ esac
 
 # required 'packagelist' to build CMaNGOS >
 # Ubuntu Server 19.10
- echo "checking.."
 packagelist=(
 autoconf
 automake
@@ -1395,9 +1413,17 @@ unzip
 zip
 zlibc
 )
-# if installed, move on >
-sudo apt-get install "${packagelist[@]}" -y &> /dev/null
+which "${packagelist[@]}" 2>&1|tee 1> /dev/null
+if [[ "$?" == 0 ]]; then
 printf '%b' "[\e[0;32mok\033[0m]"
+else
+sudo apt-get install "${packagelist[@]}" -y &> /dev/null
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+echo -e "\e[42Installation failed\e[0m"
+fi
+fi
  echo
  read -r -p "Press Enter to continue" </dev/tty
  echo
@@ -1598,7 +1624,17 @@ fi
 mkdir "$folder_wow"/backup &> /dev/null
 mkdir "$folder_wow"/backup/old &> /dev/null
 cp "$folder_wow"/backup/*.sql "$folder_wow"/backup/old &> /dev/null
-sudo apt-get install zip -y &> /dev/null
+which zip 2>&1|tee 1> /dev/null
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+sudo apt-get install zip -y
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+echo -e "\e[42Installation failed\e[0m"
+fi
+fi
 cd "$folder_wow"/backup/old/ || exit ; zip "$server_name.zip" "$folder_wow"/backup/*.sql &> /dev/null
 find "$folder_wow"/backup/*.sql -type d -ctime +10 -exec rm -rf {} \; &> /dev/null
 find "$folder_wow"/backup/old/*.sql -type d -ctime +10 -exec rm -rf {} \; &> /dev/null
@@ -1642,7 +1678,17 @@ packagelist=(
 mysql-server
 mysql-client
 )
+which "${packagelist[@]}" 2>&1|tee 1> /dev/null
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
 sudo apt-get install "${packagelist[@]}" -y &> /dev/null
+if [[ "$?" == 0 ]]; then
+printf '%b' "[\e[0;32mok\033[0m]"
+else
+ echo -e "\e[42Installation failed\e[0m"
+fi
+fi
 
 # Delete and start over ? >
 
