Update mangos

diff --git a/mangos b/mangos
--- a/mangos
+++ b/mangos
@@ -13,8 +13,8 @@
 # C(ontinued)-MaNGOS (Classic fork)
 
 # By Rainman
-# V20200207
-# 4.0.7.2
+# V20202207
+# 4.0.9.3
 
 # codes >
 while :; do
@@ -532,7 +532,7 @@ Are You Sure? (y/n) " -n 1 -r
 
       printf '%b' " <------------------------------------------------------------------------------>\e[31m
                     \e[0;32mCMaNGOS (Classic fork) - Command Center\e[31m
-            \e[0;33m[ C(ontinued)-MaNGOS Helper, admin helper tool v4.0.7.2 ]\033[0m
+            \e[0;33m[ C(ontinued)-MaNGOS Helper, admin helper tool v4.0.9.3 ]\033[0m
 
       $cm_uptime
 
@@ -1219,7 +1219,7 @@ EOF
       sudo mkdir "$folder_wow" &>/dev/null
       sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
       cd "$folder_wow" || exit
-      git clone https://github.com/cmangos/mangos-classic.git 2>/dev/null
+      git clone https://github.com/cmangos/mangos-classic.git
       echo "Done"
       sleep 1
     else
@@ -1256,14 +1256,15 @@ EOF
       sudo mkdir "$folder_wow" &>/dev/null
       sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
       cd "$folder_wow" || exit
-      git clone https://github.com/cmangos/classic-db.git 2>/dev/null
-      cd "$folder_wow" || exit
+      git clone https://github.com/cmangos/classic-db.git
+      cd "$folder_db" || exit
       ./InstallFullDB.sh
-      nano InstallFullDB.config
       echo "Done"
       sleep 1
     else
       # check for updates >
+
+      # check if 'classic-db' exist >
 
       # Classic Database (classic-db)
 
@@ -1294,7 +1295,7 @@ EOF
       sudo mkdir "$folder_helper" &>/dev/null
       sudo chown -R "${user:?}":"${group:?}" "$folder_helper"
       cd "$folder_helper" || exit
-      git clone https://github.com/Daedalus-code/cmangos-script.git 2>/dev/null
+      git clone https://github.com/Daedalus-code/cmangos-script.git
       echo "Done"
       sleep 1
     else
@@ -1319,6 +1320,13 @@ EOF
       fi
     # check if 'cmangos-script' exist done
     fi
+    # check if 'InstallFullDB.config' exist >
+    FILE="$folder_db/InstallFullDB.config"
+    if [ ! -f "$FILE" ]; then
+      cd "$folder_db" || exit
+      ./InstallFullDB.sh &>/dev/null
+    fi
+    # check if 'InstallFullDB.config' exist done
     echo
     read -r -p "Press Enter to continue" </dev/tty
     echo
@@ -2034,27 +2042,31 @@ database user, client/server is needed."
       read -r -p "Continue? (y/n) " -n 1 -r
       echo
       if [[ $REPLY =~ ^[Yy]$ ]]; then
+        read -r -p "Restart local database services? (y/n) " -n 1 -r
+        echo
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
 
-        # restart mysql service, if it exists >
-        if sudo service mysql status 2>/dev/null | grep -E 'mysql'; then
-          echo "No database system found
+          # restart mysql service, if it exists >
+          if sudo service mysql status 2>/dev/null | grep -E 'mysql'; then
+            echo "No database system found
 Please install mysql or mariadb database/client"
-          echo
-          exit
-        else
-          sudo service mysql stop &>/dev/null
-          sudo service mysql restart &>/dev/null
-        fi
+            echo
+            exit
+          else
+            sudo service mysql stop &>/dev/null
+            sudo service mysql restart &>/dev/null
+          fi
 
-        # restart mariadb service, if it exists >
-        if sudo service mariadb status 2>/dev/null | grep -E 'mariadb'; then
-          echo "No database system found
+          # restart mariadb service, if it exists >
+          if sudo service mariadb status 2>/dev/null | grep -E 'mariadb'; then
+            echo "No database system found
 Please install mysql or mariadb database/client"
-          echo
-          exit
-        else
-          sudo service mariadb stop &>/dev/null
-          sudo service mariadb restart &>/dev/null
+            echo
+            exit
+          else
+            sudo service mariadb stop &>/dev/null
+            sudo service mariadb restart &>/dev/null
+          fi
         fi
 
         printf "\e[0;31mShutting down\033[0m realmd/mangosd service"
@@ -3968,93 +3980,102 @@ Check log for which database needs 'applying updates'"
 
   "e")
 
-    read -r -p "Edit config files? (nano) (y/n) " -n 1 -r
-    echo
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
+    # check if 'mangosd.conf.dist' exist >
+    FILE="$folder_core/run/etc/mangosd.conf.dist"
+    if [ ! -f "$FILE" ]; then
+      echo "Core not compiled!"
+      echo
+      read -r -p "Press Enter to continue" </dev/tty
+      echo
+    else
+      read -r -p "Edit config files? (nano) (y/n) " -n 1 -r
+      echo
+      if [[ $REPLY =~ ^[Yy]$ ]]; then
 
-      title="       Save config without .dist
+        title="       Save config without .dist
     ================================
           Server configuration
 "
-      echo
-      prompt="
+        echo
+        prompt="
 
 Choose number ->
 
 >"
-      echo
-      options=(
+        echo
+        options=(
 
-        "mangos.conf.dist"
+          "mangos.conf.dist"
 
-        "realmd.conf.dist"
+          "realmd.conf.dist"
 
-        "playerbot.conf.dist"
+          "playerbot.conf.dist"
 
-        "ahbot.conf.dist"
+          "ahbot.conf.dist"
 
-        "mangos.conf"
+          "mangos.conf"
 
-        "realmd.conf"
+          "realmd.conf"
 
-        "playerbot.conf"
+          "playerbot.conf"
 
-        "ahbot.conf"
+          "ahbot.conf"
 
-      )
+        )
 
-      echo "$title"
-      PS3="$prompt "
-      select opt in "${options[@]}" "Quit"; do
+        echo "$title"
+        PS3="$prompt "
+        select opt in "${options[@]}" "Quit"; do
 
-        case "$REPLY" in
+          case "$REPLY" in
 
-        1)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/mangosd.conf.dist
-          ;;
-        2)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/realmd.conf.dist
-          ;;
-        3)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/playerbot.conf.dist
-          ;;
-        4)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/ahbot.conf.dist
-          ;;
+          1)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/mangosd.conf.dist
+            ;;
+          2)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/realmd.conf.dist
+            ;;
+          3)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/playerbot.conf.dist
+            ;;
+          4)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/ahbot.conf.dist
+            ;;
 
-        5)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/mangosd.conf
-          ;;
-        6)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/realmd.conf
-          ;;
-        7)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/playerbot.conf
-          ;;
-        8)
-          echo "You picked $opt $REPLY"
-          nano "$folder_core"/run/etc/ahbot.conf
-          ;;
+          5)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/mangosd.conf
+            ;;
+          6)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/realmd.conf
+            ;;
+          7)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/playerbot.conf
+            ;;
+          8)
+            echo "You picked $opt $REPLY"
+            nano "$folder_core"/run/etc/ahbot.conf
+            ;;
 
-        $((${#options[@]} + 1)))
-          echo "
+          $((${#options[@]} + 1)))
+            echo "
  See you next time!
  "
-          break
-          ;;
-        *)
-          echo "Invalid option. Try another one."
-          continue
-          ;;
-        esac
-      done
+            break
+            ;;
+          *)
+            echo "Invalid option. Try another one."
+            continue
+            ;;
+          esac
+        done
+      fi
     fi
 
     ;;
