Update mangos

diff --git a/mangos b/mangos
--- a/mangos
+++ b/mangos
@@ -13,8 +13,8 @@
 # C(ontinued)-MaNGOS (Classic fork)
 
 # By Rainman
-# V20200202
-# 2.4.6.6
+# V20200302
+# 2.5.5.5
 
 # Menusystem >
 
@@ -516,7 +516,7 @@ fi
 
 printf '%b' " <------------------------------------------------------------------------------>\e[31m
                     \e[0;32mCMaNGOS (Classic fork) - Command Center\e[31m
-            \e[0;33m[ C(ontinued)-MaNGOS Helper, admin helper tool v2.4.6.6 ]\033[0m
+            \e[0;33m[ C(ontinued)-MaNGOS Helper, admin helper tool v2.5.5.5 ]\033[0m
 
       $cm_uptime
 
@@ -1212,14 +1212,96 @@ fi
 
 # Update CMaNGOS ? >
 
+echo "checking.."
+# codes >
+sudo apt-get install dialog -y &> /dev/null
+# codes done
+HEIGHT=15
+WIDTH=50
+CHOICE_HEIGHT=6
+BACKTITLE="update CMaNGOS"
+TITLE="Update classic-mangos [core]"
+MENU="Choose one of the following options:"
+
+OPTIONS=(1 "Compile latest build"
+         2 "Fresh install (delete /build)"
+         3 "Install required packagelist"
+         4 "Reset --hard origin/master"
+         5 "Edit config files (nano)"
+         6 "Setup 'systemd Services'")
+
+CHOICE=$(dialog --clear \
+               --backtitle "$BACKTITLE" \
+               --title "$TITLE" \
+               --menu "$MENU" \
+               $HEIGHT $WIDTH $CHOICE_HEIGHT \
+               "${OPTIONS[@]}" \
+               2>&1 >/dev/tty)
+
+clear
+case $CHOICE in
+
+# compile latest build >
+
+"1")
+
+ echo "Shutting down Services.."
+ echo -ne '(0%)\r'
+sleep 1
+sudo service realmd stop &> /dev/null
+ echo -ne '(50%)\r'
+ sleep 1
+sudo service mangosd stop &> /dev/null
+ echo -ne '(100%)\r'
+ sleep 1
+sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
+mkdir "$folder_core"/run/logs &> /dev/null
+mkdir "$folder_core"/run/logs/old &> /dev/null
+touch "$folder_core"/run/logs/Server.log &> /dev/null
+cp "$folder_core"/run/logs/*.log "$folder_core"/run/logs/old
+# ahbot.conf
+cp "$folder_core"/run/etc/ahbot.conf.dist "$folder_core"/run/etc/ahbot.conf.dist &> /dev/null
+# new compile, new system logs >
+rm -f "$folder_core"/run/logs/DBErrors.log "$folder_core"/run/logs/EventAIErrors.log &> /dev/null
+# done
+sudo chown -R "$user":"$group" "$folder_wow"
+cd "${folder_build:?}" || exit
+# double quotes ("") and single quotes ('') around > $cmake < will mess things up.
+# shellcheck disable=SC2086
+cmake .. ${cmake:?}
+cd "$folder_build" || exit
+make
  echo
-printf "Update classic-mangos [\e[1;32mcore\033[0m] ?"
+printf "Select install operation"
  echo
+ echo " 1) make install"
+ echo " 2) checkinstall with backup"
  echo
- read -r -p "Are you sure? (y/n) " -n 1 -r
+read -r n
+case $n in
+1) echo "make install"
+cd "$folder_build" || exit
+sudo make install
+;;
+2) echo "checkinstall"
+cd "$folder_build" || exit
+sudo checkinstall
+;;
+*) echo "invalid option"
+;;
+esac
  echo
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
+ read -r -p "Press Enter to continue" </dev/tty
+ echo
+
+ ;;
+
+# compile latest build done
+
+# Build from scratch >
+
+"2")
+
  echo "Shutting down Services.."
  echo -ne '(0%)\r'
  sleep 1
@@ -1229,14 +1311,64 @@ sudo service realmd stop &> /dev/null
 sudo service mangosd stop &> /dev/null
  echo -ne '(100%)\r'
  sleep 1
-printf "Updating mangos-classic (\e[1;32mcore\033[0m).."
-echo
-read -r -p "Install required packagelist? (y/n) " -n 1 -r
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
-echo "Installing required packagelist.."
+cd || exit
+sudo mkdir wow &> /dev/null
+sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
+sudo rm -r "$folder_core"/build/ &> /dev/null
+cd "$folder_wow" || exit
+git clone https://github.com/cmangos/mangos-classic.git 2> /dev/null
+sudo mkdir "$folder_core"/build &> /dev/null
+sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
+mkdir "$folder_core"/run/logs &> /dev/null
+mkdir "$folder_core"/run/logs/old &> /dev/null
+touch "$folder_core"/run/logs/Server.log &> /dev/null
+cp "$folder_core"/run/logs/*.log "$folder_core"/run/logs/old
+# ahbot.conf
+cp "$folder_core"/run/etc/ahbot.conf.dist "$folder_core"/run/etc/ahbot.conf.dist &> /dev/null
+# new compile, new system logs >
+rm -f "$folder_core"/run/logs/DBErrors.log "$folder_core"/run/logs/EventAIErrors.log &> /dev/null
+# done
+sudo chown -R "$user":"$group" "$folder_wow"
+cd "${folder_build:?}" || exit
+# double quotes ("") and single quotes ('') around > $cmake < will mess things up.
+# shellcheck disable=SC2086
+cmake .. ${cmake:?}
+cd "$folder_build" || exit
+make
+ echo
+printf "Select install operation"
+ echo
+ echo " 1) make install"
+ echo " 2) checkinstall with backup"
+ echo
+read -r n
+case $n in
+1) echo "make install"
+cd "$folder_build" || exit
+sudo make install
+;;
+2) echo "checkinstall"
+cd "$folder_build" || exit
+sudo checkinstall
+;;
+*) echo "invalid option"
+;;
+esac
+ echo
+ read -r -p "Press Enter to continue" </dev/tty
+ echo
+
+ ;;
+
+# Build from scratch done
+
+# install packagelist >
+
+"3")
+
 # required 'packagelist' to build CMaNGOS >
 # Ubuntu Server 19.10
+ echo "checking.."
 packagelist=(
 autoconf
 automake
@@ -1265,112 +1397,63 @@ zlibc
 )
 # if installed, move on >
 sudo apt-get install "${packagelist[@]}" -y &> /dev/null
-fi
+printf '%b' "[\e[0;32mok\033[0m]"
+ echo
+ read -r -p "Press Enter to continue" </dev/tty
+ echo
+
+ ;;
+
+# install packagelist done
+
 # reset --hard origin/master ? >
 
- echo
- read -r -p "Reset --hard origin/master && git pull? (y/n) " -n 1 -r
- echo
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
+"4")
+
+ echo "checking.."
 cd "$folder_core" || exit
 git reset --hard origin/master
-git pull
-fi
+printf '%b' "[\e[0;32mok\033[0m]"
+ echo
+ read -r -p "Press Enter to continue" </dev/tty
+ echo
 
 # reset --hard origin/master done
 
-# Build from scratch ? >
-
- read -r -p "Fresh install? (delete /build) (y/n) " -n 1 -r
- echo
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
-cd || exit
-sudo mkdir wow &> /dev/null
-sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
-sudo rm -r "$folder_core"/build/ &> /dev/null
-cd "$folder_wow" || exit
-git clone https://github.com/cmangos/mangos-classic.git 2> /dev/null
-sudo mkdir "$folder_core"/build &> /dev/null
-fi
-
-# Build from scratch done
-
-sudo chown -R "${user:?}":"${group:?}" "$folder_wow"
-mkdir "$folder_core"/run/logs &> /dev/null
-mkdir "$folder_core"/run/logs/old &> /dev/null
-touch "$folder_core"/run/logs/Server.log &> /dev/null
-cp "$folder_core"/run/logs/*.log "$folder_core"/run/logs/old
-# ahbot.conf
-cp "$folder_core"/run/etc/ahbot.conf.dist "$folder_core"/run/etc/ahbot.conf.dist &> /dev/null
-# new compile, new system logs >
-rm -f "$folder_core"/run/logs/DBErrors.log "$folder_core"/run/logs/EventAIErrors.log &> /dev/null
-# done
-sudo chown -R "$user":"$group" "$folder_wow"
-cd "${folder_build:?}" || exit
-# double quotes ("") and single quotes ('') around > $cmake < will mess things up.
-# shellcheck disable=SC2086
-cmake .. ${cmake:?}
-cd "$folder_build" || exit
-make
- echo
-printf "Select install operation"
- echo
- echo " 1) make install"
- echo " 2) checkinstall with backup"
- echo
- read -r n
-case $n in
- 1) echo "make install"
-cd "$folder_build" || exit
-sudo make install
  ;;
- 2) echo "checkinstall"
-cd "$folder_build" || exit
-sudo checkinstall
- ;;
- *) echo "invalid option"
- ;;
-esac
- echo
 
-# Edit/Copy config files ? >
+"5")
 
- read -r -p "Edit config files? (nano) (y/n) " -n 1 -r
- echo
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
+# Edit/Copy config files >
+
 title="       Save config without .dist
-    ================================
-          Server configuration
+   ================================
+         Server configuration
 "
  echo
 prompt="
-
 Choose number ->
-
 >"
  echo
 options=(
 
- "mangos.conf.dist"
+"mangos.conf.dist"
 
- "realmd.conf.dist"
+"realmd.conf.dist"
 
- "playerbot.conf.dist"
+"playerbot.conf.dist"
 
- "ahbot.conf.dist"
+"ahbot.conf.dist"
 
- "mangos.conf"
+"mangos.conf"
 
- "realmd.conf"
+"realmd.conf"
 
- "playerbot.conf"
+"playerbot.conf"
 
- "ahbot.conf"
+"ahbot.conf"
 
- )
+)
 
  echo "$title"
 PS3="$prompt "
@@ -1398,21 +1481,21 @@ nano "$folder_core"/run/etc/ahbot.conf;;
 
 $(( ${#options[@]}+1 )) ) echo "
 See you next time!
-"; break;;
+ "; break;;
  *) echo "Invalid option. Try another one.";continue;;
 esac
 done
-fi
 
 # Edit/Copy config files done
+
+ ;;
 
 # install systemd Services >
 # Ubuntu 19.10
 
- read -r -p "Setup 'systemd Services' ? (y/n) " -n 1 -r
- echo
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
+"6")
+
+ echo "checking.."
 # /etc/systemd/system/realmd.service
  echo "[Unit]
 Description=WoW Vanilla realmd service
@@ -1447,24 +1530,30 @@ WantedBy=multi-user.target" > "$folder_wow"/mangosd.service 2> /dev/null
 # install services >
 sudo mv "$folder_wow"/*.service /etc/systemd/system/ &> /dev/null
 sudo systemctl daemon-reload
-sleep 1
+ sleep 1
 # enable services >
 sudo systemctl enable realmd
-sleep 1
+ sleep 1
 sudo systemctl enable mangosd
  echo
-printf '%b' "Check:
+printf '%b' "[\e[0;32mok\033[0m]
+
+Check:
+
 /etc/systemd/system/'\e[0;35mrealmd.service\033[0m'
 /etc/systemd/system/'\e[0;35mmangosd.service\033[0m'
+
 for correct information, or just restart server."
  echo
  echo
-fi
-
  read -r -p "Press Enter to continue" </dev/tty
-fi
+ echo
 
 # install systemd Services done
+
+ ;;
+
+esac
 
 # Update CMaNGOS done
 
