Update server_menu

diff --git a/include/server_menu b/include/server_menu
--- a/include/server_menu
+++ b/include/server_menu
@@ -6,9 +6,12 @@
 
 # By Rainman
 # V20210203-barebone
-# 0.5.3.7
+# 0.7.2.0
 
 # https://www.linuxatemyram.com, num num num
+
+# wget https://raw.githubusercontent.com/Daedalus-code/cmangos-script/master/include/server_menu
+# bash server_menu
 
 # shellcheck disable=SC2034
 
@@ -75,9 +78,9 @@ fi
 
 DIALOG_CANCEL=1
 DIALOG_ESC=255
-HEIGHT=21
+HEIGHT=22
 WIDTH=45
-CHOICE_HEIGHT=14
+CHOICE_HEIGHT=15
 
 BACKTITLE="CMaNGOS features"
 TITLE="<  C M a N G O S - M e n u  >"
@@ -89,7 +92,8 @@ OPTIONS=(Manage "Start/Stop Server"
   Core "Core Configuration"
   Data "Database Configuration"
   Bots "Bot Configuration"
-  Maps "P2P/Extract/Import Maps"
+  Maps "Extract/Import Maps"
+  Seed "P2P Dashboard"
   Remote "Remote Access"
   Realm "Realm Information"
   System "System Information"
@@ -388,9 +392,188 @@ while true; do
 
     ;;
 
+  Seed)
+
+    # get remote information from transmission, create a file
+    transmission-remote -t all -i >/var/log/ms/transmission_list 2>&1
+    # pidof transmission-daemon, cli, pid/status
+    PIDOFP2P_CLI=$(pidof transmission-cli 2>&1)
+    PIDOFP2P_DAE=$(pidof transmission-daemon 2>&1)
+    # is transmission-cli installed?
+    if ! [ -x "$(command -v transmission-cli)" ]; then
+      P2P_TMISSION="Not Found"
+      P2P_INTRANET="0.0.0.0:9091"
+      P2P_SEED_NME="expansion_maps.zip"
+      P2P_PEERS_CO="N/A"
+      P2P_DOWNLOAD="N/A "
+      P2P_UPLOADED="N/A "
+      P2P_STATUS="N/A"
+      P2P_PROGRE="N/A"
+      P2P_RATIOS="N/A"
+      P2P_PEERS_S2=""
+      P2P_PEERS_DL=""
+      P2P_SLASH_SM=""
+    else
+      if [ -f /var/log/ms/transmission_list ]; then
+        # cat that file
+        P2P_INFO=$(cat /var/log/ms/transmission_list 2>&1)
+        # peers, connected, seeding to, downloading from
+        P2P_PEERS_CO=$(echo "$P2P_INFO" 2>&1 | grep "Peers" 2>&1 | awk '{ print $4 }' 2>&1 | awk -F, '{ print $1 }' 2>&1)
+        P2P_PEERS_S2=$(echo "$P2P_INFO" 2>&1 | grep "Peers" 2>&1 | awk '{ print $7 }' 2>&1 | awk -F, '{ print $1 }' 2>&1)
+        P2P_PEERS_DL=$(echo "$P2P_INFO" 2>&1 | grep "Peers" 2>&1 | awk '{ print $10 }' 2>&1)
+        # get progress
+        if echo "$P2P_INFO" 2>&1 | grep -q -o "Percent Done: 100%" 2>&1; then
+          P2P_SEED_NME="vanilla_maps.zip"
+        else
+          P2P_SEED_NME="vanilla_maps.???"
+        fi
+        # get progress
+        if echo "$P2P_INFO" 2>&1 | grep -q -o "Percent Done: 100%" 2>&1; then
+          P2P_PROGRE="100%"
+        else
+          P2P_PROGRE=$(echo "$P2P_INFO" 2>&1 | grep -Eo "Percent Done:.*" 2>&1 |
+            awk '{ print $3 }' 2>&1)
+        fi
+        # get download stats
+        P2P_DOWNLOAD=$(echo "$P2P_INFO" 2>&1 | grep -o "Downloaded:.*" 2>&1 |
+          awk '{ print $2 }' 2>&1)
+        P2P_DOWNLOAD=$(echo "$P2P_DOWNLOAD ")
+        # get upload stats
+        P2P_UPLOADED=$(echo "$P2P_INFO" 2>&1 | grep -o "Uploaded:.*" 2>&1 |
+          awk '{ print $2 }' 2>&1)
+        P2P_UPLOADED=$(echo "$P2P_UPLOADED ")
+        # get ratio
+        P2P_RATIOS=$(echo "$P2P_INFO" 2>&1 | grep -o "Ratio:.*" 2>&1 |
+          awk '{ print $2 }' 2>&1)
+        # get status
+        P2P_STATUS=$(echo "$P2P_INFO" 2>&1 | grep -o "State:.*" 2>&1 |
+          awk '{ print $2 }' 2>&1)
+      fi
+      # transmission-daemon status
+      case "$(pidof transmission-daemon 2>&1 | wc -w 2>&1)" in
+
+      "0") # not runnning
+
+        P2P_TMISSION="Offline"
+        P2P_INTRANET="0.0.0.0:9091"
+        P2P_SEED_NME="expansion_maps.zip"
+        P2P_PEERS_CO="N/A"
+        P2P_DOWNLOAD="N/A "
+        P2P_UPLOADED="N/A "
+        P2P_STATUS="N/A"
+        P2P_PROGRE="N/A"
+        P2P_RATIOS="N/A"
+        P2P_PEERS_S2=""
+        P2P_PEERS_DL=""
+        P2P_SLASH_SM=""
+
+        ;;
+
+      "1") # running
+
+        P2P_TMISSION="Online"
+        P2P_INTRANET="$(hostname -I 2>&1 | xargs 2>&1):9091"
+        P2P_SEED_NME="vanilla_maps.zip"
+        P2P_SLASH_SM="/"
+
+        ;;
+
+      "*") # something
+
+        P2P_TMISSION="Online+"
+        P2P_INTRANET="$(hostname -I 2>&1 | xargs 2>&1):9091"
+        P2P_PEERS_CO="N/A"
+        P2P_PEERS_S2="N/A"
+        P2P_PEERS_DL="N/A"
+        P2P_SLASH_SM=""
+
+        ;;
+
+      esac
+    fi
+
+    # p2p dashboard
+    P2P_DASH=$(echo "
+SeedBox..: $P2P_TMISSION
+Access...: $P2P_INTRANET
+Filename.: $P2P_SEED_NME
+Download.: ${P2P_DOWNLOAD:?}Unlimited
+Upload...: ${P2P_UPLOADED:?}128kb/s
+Status...: $P2P_STATUS
+Progress.: $P2P_PROGRE
+Ratio....: $P2P_RATIOS
+Peers....: $P2P_PEERS_CO$P2P_SLASH_SM$P2P_PEERS_S2$P2P_SLASH_SM$P2P_PEERS_DL
+")
+    RESULT=$(
+      echo "CMaNGOS Maps (P2P/Import)"
+      echo "$P2P_DASH"
+    )
+    display_result "SeedBox"
+    # CODE MISSING !!
+
+    ;;
+
   Maps)
 
-    # CODE MISSING !!
+    DIALOG_CANCEL=1
+    DIALOG_ESC=255
+    HEIGHT=10
+    WIDTH=40
+    CHOICE_HEIGHT=3
+    BACKTITLE="Install, Import, Maps"
+    TITLE="Server Expansion Maps"
+    MENU="Choose one of the following options:"
+
+    OPTIONS=(1 "Extract Maps (from client)"
+      2 "Install, Import, Seed Maps"
+      3 "Stop, Remove SeedBox")
+
+    exec 3>&1
+    CHOICE=$(dialog --clear \
+      --backtitle "$BACKTITLE" \
+      --title "$TITLE" \
+      --cancel-label "Exit" \
+      --menu "$MENU" \
+      $HEIGHT $WIDTH $CHOICE_HEIGHT \
+      "${OPTIONS[@]}" \
+      2>&1 1>&3)
+
+    # error status
+    EXIT_STATUS=$?
+    exec 3>&-
+    case $EXIT_STATUS in
+    "$DIALOG_CANCEL")
+      clear
+      echo "Program terminated."
+      exit
+      ;;
+    "$DIALOG_ESC")
+      clear
+      echo "Program aborted." >&2
+      exit 1
+      ;;
+    esac
+
+    clear
+    case $CHOICE in
+
+    1) ;;
+
+      # CODE MISSING !!
+
+    2)
+
+      # CODE MISSING !!
+
+      ;;
+
+    3)
+
+      # CODE MISSING !!
+
+      ;;
+
+    esac
 
     ;;
 
