Update server_menu

diff --git a/include/server_menu b/include/server_menu
--- a/include/server_menu
+++ b/include/server_menu
@@ -5,19 +5,47 @@
 ################################# .. ALPHA VERSION!
 
 # By Rainman
-# V20212502
-# 0.2.1.4
+# V20212502-barebone
+# 0.2.7.6
 
-# references:
+# sources:
+# https://medium.com/@takanori.ishikawa/how-to-show-progress-bar-while-unzipping-tons-of-files-7b1ea7a84b01
 # https://askubuntu.com/questions/1705/how-can-i-create-a-select-menu-in-a-shell-script
 # https://linuxcommand.org/lc3_adv_dialog.php
+
+# check, install missing dialog
+if ! [ -x "$(command -v dialog)" ]; then
+  echo "Dialog Not Installed"
+  sleep 1
+  # uname -a outputs linux
+  if uname -a 2>&1 | grep -q -Eo "Linux"; then
+    echo "Found Linux, Please Wait"
+    # linux
+    sudo apt-get install dialog -y 2>&1
+    # uname -a outputs darwin
+  elif uname -a 2>&1 | grep -q -Eo "Darwin"; then
+    echo "Found Darwin, Please Wait"
+    if ! [ -x "$(command -v brew)" ]; then
+      echo "Brew Not Found"
+      # install brew
+      read -r -p "Install Brew? y/n "
+      if [[ $REPLY =~ ^[Yy]$ ]]; then
+        echo "Please Wait"
+        # https://brew.sh
+        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+      fi
+    fi
+    # darwin
+    brew install dialog 2>&1
+  fi
+fi
 
 export NCURSES_NO_UTF8_ACS=1
 DIALOG_CANCEL=1
 DIALOG_ESC=255
-HEIGHT=20
+HEIGHT=21
 WIDTH=45
-CHOICE_HEIGHT=15
+CHOICE_HEIGHT=14
 
 BACKTITLE="CMaNGOS features"
 TITLE="<  C M a N G O S - M e n u  >"
@@ -35,7 +63,8 @@ OPTIONS=(Start "Start Server"
   Uninstall "Remove Everything"
   System "System Information"
   Disk "Display Disk Space"
-  Repo "Display Repo Space")
+  Repo "Display Repo Space"
+  Debug "Debug Script")
 
 while true; do
   exec 3>&1
@@ -93,97 +122,114 @@ while true; do
     else
       DB_STATUS="0"
     fi
-    REPO_STATUS=$(echo "$CORE_STATUS+$DB_STATUS" 2>/dev/null | bc 2>/dev/null)
+    REPO_STATUS=$(echo "$CORE_STATUS+$DB_STATUS" 2>&1 | bc 2>&1)
     if [[ "$REPO_STATUS" -eq "2" ]]; then
       # all set with repos, core and database
       RESULT=$(echo "Found Install")
       display_result "Everything Set"
-      # CODE
+      # CODE MISSING !!
     else
       # all set with repos, core and database
       RESULT=$(echo "Nothing!")
       display_result "No Install Found"
-      # CODE
+      # CODE MISSING !!
     fi
 
     ;;
 
   Stop)
 
-    # Stop CODE
+    # CODE MISSING !!
 
     ;;
 
   Restart)
 
-    # Restart CODE
+    # CODE MISSING !!
 
     ;;
 
   Config)
 
-    # Config CODE
+    # CODE MISSING !!
 
     ;;
 
   Update)
 
-    # Update CODE
+    # CODE MISSING !!
 
     ;;
 
   Install)
 
-    # Install CODE
+    # CODE MISSING !!
 
     ;;
 
   Maps)
 
-    # Maps CODE
+    echo "Importing Maps"
+    N_FILES=$(unzip -l /seedbox/vanilla_maps.zip 2>&1 |
+      grep -E ".map|.vmo|.vmtile|.vmtree|temp_gameobject_models|.dbc|.mmtile|.mmap" 2>&1 |
+      wc -l 2>&1)
+    unzip -o /seedbox/vanilla_maps.zip -d /home/wow/mangos-classic/run/ 2>&1 |
+      pv -l -s "${N_FILES[0]}" >/dev/null
+    # CODE MISSING !!
 
     ;;
 
   Database)
 
-    # Database CODE
+    # CODE MISSING !!
 
     ;;
 
   Remote)
 
-    # Remote CODE
+    # CODE MISSING !!
 
     ;;
 
   System)
 
     # free Memory
-    SYSTEM_FREE_MEM=$(free --mega 2>/dev/null | grep "Mem" 2>/dev/null | awk '{ print $4 }' 2>/dev/null)
+    SYSTEM_FREE_MEM=$(free --mega 2>&1 | grep "Mem" 2>&1 | awk '{ print $4 }' 2>&1)
     # total Memory
-    SYSTEM_TOTAL_MEM=$(free --mega 2>/dev/null | grep "Mem" 2>/dev/null | awk '{ print $2 }' 2>/dev/null)
+    SYSTEM_TOTAL_MEM=$(free --mega 2>&1 | grep "Mem" 2>&1 | awk '{ print $2 }' 2>&1)
     # free Space, mmc block device #0, partition #2, partition #2, dev/root, overlay
-    SYSTEM_HDD=$(df -h 2>/dev/null | grep -E "mmcblk0p2|mmcblk0p3|/dev/root|overlay" 2>/dev/null | awk '{ print $3 }' 2>/dev/null)
+    SYSTEM_HDD=$(df -h 2>&1 | grep -E "mmcblk0p2|mmcblk0p3|/dev/root|overlay" 2>&1 |
+      awk '{ print $3 }' 2>&1)
     # percentage of total used
-    SYSTEM_HDD_P=$(df -h 2>/dev/null | grep -E "mmcblk0p2|mmcblk0p3|/dev/root|overlay" 2>/dev/null | awk '{ print $5 }' 2>/dev/null)
+    SYSTEM_HDD_P=$(df -h 2>&1 | grep -E "mmcblk0p2|mmcblk0p3|/dev/root|overlay" 2>&1 |
+      awk '{ print $5 }' 2>&1)
     # total size
-    SYSTEM_HDD_T=$(df -h 2>/dev/null | grep -E "mmcblk0p2|mmcblk0p3|/dev/root|overlay" 2>/dev/null | awk '{ print $2 }' 2>/dev/null)
+    SYSTEM_HDD_T=$(df -h 2>&1 | grep -E "mmcblk0p2|mmcblk0p3|/dev/root|overlay" 2>&1 |
+      awk '{ print $2 }' 2>&1)
     # operating system, cpu type, kernal release
-    SYSTEM_CPU=$(uname -p 2>/dev/null)
-    SYSTEM_OS=$(uname -o 2>/dev/null)
-    SYSTEM_KR=$(uname -r 2>/dev/null)
-    # system load, uptime
-    SYSTEM_LOAD=$(uptime 2>/dev/null | grep -o "load.*" 2>/dev/null)
-    SYSTEM_UPTIME=$(uptime 2>/dev/null | grep -Eo "[0-9]+ days, [0-9]+:[0-9]+" 2>/dev/null)
+    SYSTEM_CPU=$(uname -p 2>&1)
+    SYSTEM_OS=$(uname -o 2>&1)
+    SYSTEM_KR=$(uname -r 2>&1)
     # cpu temp
-    SYSTEM_TEMP=$(awk '{print $cpu/1000}' /sys/class/thermal/thermal_zone0/temp 2>/dev/null | cut -c -4 2>/dev/null)
+    if uname -a 2>&1 | grep -q -Eo "aarch64|arm"; then
+      SYSTEM_TEMP=$(awk '{print $cpu/1000}' /sys/class/thermal/thermal_zone0/temp 2>&1 |
+        cut -c -4 2>&1)
+      SYSTEM_TEMP=$(echo "($SYSTEM_TEMP)")
+    else
+      SYSTEM_TEMP=""
+    fi
+    # system load, uptime
+    SYSTEM_LOAD=$(uptime 2>&1 | grep -o "load.*" 2>&1)
+    SYSTEM_UPTIME_DAYS=$(uptime 2>&1 | grep -Eo "[0-9]+ days" 2>&1)
+    SYSTEM_UPTIME_HOURS=$(uptime 2>&1 | awk '{ print $5 }' 2>&1 |
+      awk -F, '{ print $1 }' 2>&1)
 
     RESULT=$(
       echo "Load.....: $SYSTEM_LOAD"
       echo "System...: $SYSTEM_KR $SYSTEM_OS"
-      echo "Uptime...: $SYSTEM_UPTIME"
+      echo "Uptime...: $SYSTEM_UPTIME_DAYS $SYSTEM_UPTIME_HOURS"
       echo "Hostname.: $HOSTNAME"
-      echo "CPU-Type.: $SYSTEM_CPU ($SYSTEM_TEMP)"
+      echo "CPU-Type.: $SYSTEM_CPU $SYSTEM_TEMP"
       echo "Memory...: $SYSTEM_FREE_MEM/$SYSTEM_TOTAL_MEM"
       echo "HDD......: $SYSTEM_HDD/$SYSTEM_HDD_T $SYSTEM_HDD_P"
     )
@@ -201,12 +247,28 @@ while true; do
   Repo)
 
     # repo space
-    REPO_SIZE=$(du -h --max-depth=1 "$HOME"/wow/ 2>/dev/null)
+    REPO_SIZE=$(du -h --max-depth=1 "$HOME"/wow/ 2>&1)
     RESULT=$(
       echo "Repositories: Core, Database & Backup"
       echo "$REPO_SIZE"
     )
     display_result "Repo Size"
+
+    ;;
+
+  Debug)
+
+    # fix ownership
+    sudo chown -R "$(whoami)":"$(whoami)" /usr/local/bin/mangos
+    # remove file
+    sudo rm /usr/local/bin/server_menu 2>/dev/null
+    # create file
+    sudo touch /usr/local/bin/server_menu 2>/dev/null
+    # chmod file
+    sudo chmod +x /usr/local/bin/server_menu 2>/dev/null
+    # nano file
+    sudo nano /usr/local/bin/server_menu 2>/dev/null
+    # CODE MISSING !!
 
     ;;
 
