Update server_menu

diff --git a/include/server_menu b/include/server_menu
--- a/include/server_menu
+++ b/include/server_menu
@@ -6,7 +6,7 @@
 
 # By Rainman
 # V20210303-barebone
-# 0.7.7.9
+# 0.7.9.4
 
 # https://www.linuxatemyram.com, num num num
 
@@ -566,15 +566,30 @@ Peers....: $P2P_PEERS_CO$P2P_SLASH_SM$P2P_PEERS_S2$P2P_SLASH_SM$P2P_PEERS_DL
     2)
 
       # remove old files
-      rm /var/tmp/optional.out &>/dev/null
+      rm /tmp/optional.out &>/dev/null
       dialog --backtitle "Start, Import, Seed Maps" \
         --title "Maps Checkbox " \
-        --checklist "Choose from following" 0 0 0 \
-        1 "CMaNGOS Classic" off \
-        2 "CMaNGOS The Burning Crusade" off \
-        3 "CMaNGOS Wrath of the Lich King" off \
-        2>/var/tmp/optional.out
-      OPTIONAL=$(cat /var/tmp/optional.out | tr -d ' ')
+        --checklist "Choose Expansion Maps for Import/Download (torrent)" 11 35 3 \
+        1 "Maps -> Classic" off \
+        2 "Maps -> TBC" off \
+        3 "Maps -> WOTLK" off \
+        2>/tmp/optional.out
+      OPTIONAL=$(cat /tmp/optional.out 2>&1 | tr -d ' ' 2>&1)
+      # error status
+      EXIT_STATUS=$?
+      exec 3>&-
+      case $EXIT_STATUS in
+      "$DIALOG_CANCEL")
+        clear
+        echo "Program terminated."
+        exit
+        ;;
+      "$DIALOG_ESC")
+        clear
+        echo "Program aborted." >&2
+        exit 1
+        ;;
+      esac
       clear
       # outputs
       CLASSIC_MAPS=$(printf '%b' "Setting up ${GR:?}Classic Maps${N0:?} for Download/Import!\n")
@@ -583,42 +598,42 @@ Peers....: $P2P_PEERS_CO$P2P_SLASH_SM$P2P_PEERS_S2$P2P_SLASH_SM$P2P_PEERS_DL
       # options
       if [[ "$OPTIONAL" -eq "1" ]]; then
         echo "$CLASSIC_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         # CODE MISSING !!
         continue
       elif [[ "$OPTIONAL" -eq "2" ]]; then
         echo "$TBC_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         # CODE MISSING !!
         continue
       elif [[ "$OPTIONAL" -eq "3" ]]; then
         echo "$WOTLK_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         # CODE MISSING !!
         continue
       elif [[ "$OPTIONAL" -eq "12" ]]; then
         echo "$CLASSIC_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         echo "$TBC_MAPS"
         # CODE MISSING !!
         continue
       elif [[ "$OPTIONAL" -eq "13" ]]; then
         echo "$CLASSIC_MAPS"
         echo "$WOTLK_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         # CODE MISSING !!
         continue
       elif [[ "$OPTIONAL" -eq "23" ]]; then
         echo "$TBC_MAPS"
         echo "$WOTLK_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         # CODE MISSING !!
         continue
       elif [[ "$OPTIONAL" -eq "123" ]]; then
         echo "$CLASSIC_MAPS"
         echo "$TBC_MAPS"
         echo "$WOTLK_MAPS"
-        rm /var/tmp/optional.out &>/dev/null
+        rm /tmp/optional.out &>/dev/null
         # CODE MISSING !!
         continue
       fi
